[build]
  command = "pip install -r requirements.txt"
  publish = "."
  functions = "functions"

[build.environment]
  FLASK_APP = "app.py"
  FLASK_ENV = "production"
  GOOGLE_CLIENT_ID = "748645327636-1scd4f35u930na2pommpajnma17eon4g.apps.googleusercontent.com"
  GOOGLE_REDIRECT_URI = "https://scan-mark.netlify.app/auth/google/callback"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
