[build]
  command = "pip install -r requirements.txt"
  publish = "."
  functions = "api"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/index.py"
  status = 200
  force = true
