services:
  - type: web
    name: scanmark
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: .
      - key: FLASK_APP
        value: app.py
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_iaL8ckJzYN7X@ep-shy-smoke-a5mn2t1d-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /health
    autoDeploy: true
